,name: Publicar no NPM

# Este workflow será acionado toda vez que uma tag de versão for criada e enviada (ex: v1.0.0)
on:
  push:
    tags:
      - 'v*' 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js e NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: 3. Instalar Dependências (Style Dictionary)
        run: npm install

      - name: 4. Rodar o Build dos Tokens
        run: npm run build # Executa o script 'build' do seu package.json

      - name: 5. Publicar no NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Usa o token que vamos salvar no GitHub